[workspace]
resolver = "2"
members = [
  "policy-styx-lib",
  "policy-styx-runner",
  "sandbox-apps/cox-demo",
  "sandbox-apps/polars-demo",
  "sandbox-apps/policy-styx",
]

[workspace.dependencies]
polars = { git = "https://github.com/hiroki-chen/polars.git", default-features = false }
policy-styx-lib = { path = "policy-styx-lib" }
policy-styx = { path = "policy-styx" }
