[package]
name = "polars-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
coxfitter = { git = "https://github.com/hiroki-chen/coxphfitter.git", rev = "29f8816" }
anyhow = "1.0.95"
chrono = { workspace = true }
polars = { workspace = true }
uuid = "1.13.1"
policy-styx-lib = { workspace = true, default-features = false }
bincode = { workspace = true, default-features = false }
