[package]
name = "policy-styx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.95"
polars = { workspace = true, features = [
  "lazy",
  "ipc",
  "top_k",
  "parquet",
  "is_in",
  "temporal",
  "cross_join",
  "dtype-date",
  "regex",
  "strings",
  "dtype-datetime",
  "semi_anti_join",
], default-features = false }
policy-styx-sys = { workspace = true }
