[package]
name = "policy-styx-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.3" }
anyhow = { workspace = true }
bincode = "1.3.3"
dcap-rs = { workspace = true, optional = true }
sha2 = { version = "0.10.8", default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
tdx = { workspace = true, optional = true }
uuid = { version = "1.13.1", features = ["serde", "v4"] }
wasi-common = "29.0.1"
wasmtime = { version = "29.0.1", features = ["runtime"] }

[features]
default = ["platform-tdx"]
platform-tdx = ["tdx", "dcap-rs"]
